"""thumbnail

Revision ID: 04ff88894118
Revises: bb1a76d17700
Create Date: 2024-05-19 22:53:57.293516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ff88894118'
down_revision: Union[str, None] = 'bb1a76d17700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.alter_column('files', 'added_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'added_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('files', 'thumbnail_url')
    # ### end Alembic commands ###
