"""indexes

Revision ID: 84922bf3033d
Revises: 5a9f746c7a4a
Create Date: 2024-05-19 14:11:57.749300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84922bf3033d'
down_revision: Union[str, None] = '5a9f746c7a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_files_room_id'), 'files', ['room_id'], unique=False)
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_index(op.f('ix_files_room_id'), table_name='files')
    # ### end Alembic commands ###
