"""aaa

Revision ID: bb1a76d17700
Revises: 84922bf3033d
Create Date: 2024-05-19 19:19:21.762692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1a76d17700'
down_revision: Union[str, None] = '84922bf3033d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('added_by', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'added_by')
    # ### end Alembic commands ###
